CPUS="1"
MEMORY="1024"

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "docker.centos.vm"

  config.vm.provider "virtualbox" do |v|
    v.name = "docker.centos.vm"
    v.memory = MEMORY
    v.cpus = CPUS
  end

  config.vm.provision :shell, privileged: false, run: "always", inline: %(
    cd /vagrant/
    bundle exec unicorn_rails -D
    sudo service nginx restart
  )

end
